name = "LineBroadenings"
uuid = "e2cc112f-28d1-4ed4-acfa-be605a9d07f6"
authors = ["Northwemko <yinyangxiangsheng@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
PhysicalConstants = "0.2"
SpecialFunctions = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
